/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AccessToken } from './models/AccessToken';
export type { Address } from './models/Address';
export type { AddressCreateSessionDto } from './models/AddressCreateSessionDto';
export type { AddressGetAllSessionResponse } from './models/AddressGetAllSessionResponse';
export type { AddressGetResponse } from './models/AddressGetResponse';
export type { AddressUpdateSessionDto } from './models/AddressUpdateSessionDto';
export type { AiAliyunAccount } from './models/AiAliyunAccount';
export type { AiAliyunAccountGetAllResponse } from './models/AiAliyunAccountGetAllResponse';
export type { AiAliyunAccountGetHistoryResponse } from './models/AiAliyunAccountGetHistoryResponse';
export type { AiAliyunAccountGetResponse } from './models/AiAliyunAccountGetResponse';
export type { AiAliyunAccountPaginatePage } from './models/AiAliyunAccountPaginatePage';
export type { AiAliyunAccountPaginateResponse } from './models/AiAliyunAccountPaginateResponse';
export type { AiAliyunMessage } from './models/AiAliyunMessage';
export type { AiAliyunOcr } from './models/AiAliyunOcr';
export type { AiAliyunOcrGetAllResponse } from './models/AiAliyunOcrGetAllResponse';
export type { AiAliyunOcrGetResponse } from './models/AiAliyunOcrGetResponse';
export type { AiAliyunOcrPaginatePage } from './models/AiAliyunOcrPaginatePage';
export type { AiAliyunOcrPaginateResponse } from './models/AiAliyunOcrPaginateResponse';
export type { AiAliyunOcrRecognizeAllText } from './models/AiAliyunOcrRecognizeAllText';
export type { AiAliyunService } from './models/AiAliyunService';
export type { AiAliyunServiceGetAllResponse } from './models/AiAliyunServiceGetAllResponse';
export type { AiAliyunServiceGetResponse } from './models/AiAliyunServiceGetResponse';
export type { AiAliyunServicePaginatePage } from './models/AiAliyunServicePaginatePage';
export type { AiAliyunServicePaginateResponse } from './models/AiAliyunServicePaginateResponse';
export type { AiAliyunSession } from './models/AiAliyunSession';
export type { AiAliyunSessionGetAllResponse } from './models/AiAliyunSessionGetAllResponse';
export type { AiAliyunSessionGetResponse } from './models/AiAliyunSessionGetResponse';
export type { AiAliyunSessionPaginatePage } from './models/AiAliyunSessionPaginatePage';
export type { AiAliyunSessionPaginateResponse } from './models/AiAliyunSessionPaginateResponse';
export type { AiBaiduAccount } from './models/AiBaiduAccount';
export type { AiBaiduAccountGetAllResponse } from './models/AiBaiduAccountGetAllResponse';
export type { AiBaiduAccountGetHistoryResponse } from './models/AiBaiduAccountGetHistoryResponse';
export type { AiBaiduAccountGetResponse } from './models/AiBaiduAccountGetResponse';
export type { AiBaiduAccountPaginatePage } from './models/AiBaiduAccountPaginatePage';
export type { AiBaiduAccountPaginateResponse } from './models/AiBaiduAccountPaginateResponse';
export type { AiBaiduMessage } from './models/AiBaiduMessage';
export type { AiBaiduOcr } from './models/AiBaiduOcr';
export type { AiBaiduOcrGetAllResponse } from './models/AiBaiduOcrGetAllResponse';
export type { AiBaiduOcrGetResponse } from './models/AiBaiduOcrGetResponse';
export type { AiBaiduOcrPaginatePage } from './models/AiBaiduOcrPaginatePage';
export type { AiBaiduOcrPaginateResponse } from './models/AiBaiduOcrPaginateResponse';
export type { AiBaiduOrcGeneralScenarios } from './models/AiBaiduOrcGeneralScenarios';
export type { AiBaiduService } from './models/AiBaiduService';
export type { AiBaiduServiceGetAllResponse } from './models/AiBaiduServiceGetAllResponse';
export type { AiBaiduServiceGetResponse } from './models/AiBaiduServiceGetResponse';
export type { AiBaiduServicePaginatePage } from './models/AiBaiduServicePaginatePage';
export type { AiBaiduServicePaginateResponse } from './models/AiBaiduServicePaginateResponse';
export type { AiBaiduSession } from './models/AiBaiduSession';
export type { AiBaiduSessionGetAllResponse } from './models/AiBaiduSessionGetAllResponse';
export type { AiBaiduSessionGetResponse } from './models/AiBaiduSessionGetResponse';
export type { AiBaiduSessionPaginatePage } from './models/AiBaiduSessionPaginatePage';
export type { AiBaiduSessionPaginateResponse } from './models/AiBaiduSessionPaginateResponse';
export type { AiServiceType } from './models/AiServiceType';
export type { AiServiceTypeGetAllResponse } from './models/AiServiceTypeGetAllResponse';
export type { AiServiceTypeGetResponse } from './models/AiServiceTypeGetResponse';
export { AliyunOcrOperates } from './models/AliyunOcrOperates';
export { AliyunOcrRecognizeAllTextType } from './models/AliyunOcrRecognizeAllTextType';
export type { Area } from './models/Area';
export type { AreaResponse } from './models/AreaResponse';
export type { AuthLoginSuccessResponse } from './models/AuthLoginSuccessResponse';
export type { AuthVerifyResponse } from './models/AuthVerifyResponse';
export { BaiduGeneralScenariosType } from './models/BaiduGeneralScenariosType';
export { BaiduOcrOperates } from './models/BaiduOcrOperates';
export type { Buffer } from './models/Buffer';
export { ChatContacts } from './models/ChatContacts';
export type { ChatContactsCreateDto } from './models/ChatContactsCreateDto';
export type { ChatContactsGetResponse } from './models/ChatContactsGetResponse';
export { ChatContactsUpdateDto } from './models/ChatContactsUpdateDto';
export { ChatMessage } from './models/ChatMessage';
export { ChatMessageCreateDto } from './models/ChatMessageCreateDto';
export type { ChatMessageGetResponse } from './models/ChatMessageGetResponse';
export type { ChatSession } from './models/ChatSession';
export type { ChatSessionCreateDto } from './models/ChatSessionCreateDto';
export type { ChatSessionCreateResponse } from './models/ChatSessionCreateResponse';
export type { ChatSessionGetResponse } from './models/ChatSessionGetResponse';
export type { CreateAiAliyunAccountDto } from './models/CreateAiAliyunAccountDto';
export type { CreateAiAliyunMessageDto } from './models/CreateAiAliyunMessageDto';
export type { CreateAiAliyunOcrDto } from './models/CreateAiAliyunOcrDto';
export type { CreateAiAliyunServiceDto } from './models/CreateAiAliyunServiceDto';
export type { CreateAiAliyunSessionDto } from './models/CreateAiAliyunSessionDto';
export type { CreateAiBaiduAccountDto } from './models/CreateAiBaiduAccountDto';
export type { CreateAiBaiduMessageDto } from './models/CreateAiBaiduMessageDto';
export type { CreateAiBaiduOcrDto } from './models/CreateAiBaiduOcrDto';
export type { CreateAiBaiduServiceDto } from './models/CreateAiBaiduServiceDto';
export type { CreateAiBaiduSessionDto } from './models/CreateAiBaiduSessionDto';
export type { CreateAiServiceTypeDto } from './models/CreateAiServiceTypeDto';
export type { CreateAiSessionDto } from './models/CreateAiSessionDto';
export type { CreateFDto } from './models/CreateFDto';
export type { CreateResourceDto } from './models/CreateResourceDto';
export type { CreateRolesDto } from './models/CreateRolesDto';
export type { CreateSuperAdminDto } from './models/CreateSuperAdminDto';
export type { CreateUsersDto } from './models/CreateUsersDto';
export type { DeleteSuccessResult } from './models/DeleteSuccessResult';
export type { F } from './models/F';
export type { FGetAllResponse } from './models/FGetAllResponse';
export type { FGetResponse } from './models/FGetResponse';
export type { File } from './models/File';
export type { FileBuffer } from './models/FileBuffer';
export type { FileDetail } from './models/FileDetail';
export type { FilesUploadDto } from './models/FilesUploadDto';
export type { FileUploadDto } from './models/FileUploadDto';
export type { FileUploadResponse } from './models/FileUploadResponse';
export type { ForumComment } from './models/ForumComment';
export type { ForumCommentCreateDto } from './models/ForumCommentCreateDto';
export type { ForumCommentGetAllResponse } from './models/ForumCommentGetAllResponse';
export type { ForumCommentGetCountResponse } from './models/ForumCommentGetCountResponse';
export type { ForumCommentGetResponse } from './models/ForumCommentGetResponse';
export type { ForumCommentPaginatePage } from './models/ForumCommentPaginatePage';
export type { ForumCommentPaginateResponse } from './models/ForumCommentPaginateResponse';
export type { ForumPost } from './models/ForumPost';
export type { ForumPostCreateDto } from './models/ForumPostCreateDto';
export type { ForumPostGetAllResponse } from './models/ForumPostGetAllResponse';
export type { ForumPostGetCountResponse } from './models/ForumPostGetCountResponse';
export type { ForumPostGetResponse } from './models/ForumPostGetResponse';
export type { ForumPostPaginatePage } from './models/ForumPostPaginatePage';
export type { ForumPostPaginateResponse } from './models/ForumPostPaginateResponse';
export { ForumPostRelation } from './models/ForumPostRelation';
export { ForumPostRelationCreateDto } from './models/ForumPostRelationCreateDto';
export type { ForumPostRelationGetAllResponse } from './models/ForumPostRelationGetAllResponse';
export type { ForumPostRelationGetCountResponse } from './models/ForumPostRelationGetCountResponse';
export type { ForumPostRelationPaginatePage } from './models/ForumPostRelationPaginatePage';
export type { ForumPostRelationPaginateResponse } from './models/ForumPostRelationPaginateResponse';
export type { ForumPostUpdateDto } from './models/ForumPostUpdateDto';
export type { ForumSection } from './models/ForumSection';
export type { ForumSectionCreateDto } from './models/ForumSectionCreateDto';
export type { ForumSectionGetAllResponse } from './models/ForumSectionGetAllResponse';
export type { ForumSectionGetResponse } from './models/ForumSectionGetResponse';
export type { ForumSectionPaginatePage } from './models/ForumSectionPaginatePage';
export type { ForumSectionPaginateResponse } from './models/ForumSectionPaginateResponse';
export type { ForumSectionUpdateDto } from './models/ForumSectionUpdateDto';
export type { GeneralScenarios } from './models/GeneralScenarios';
export type { GetJssdkSignatureDto } from './models/GetJssdkSignatureDto';
export type { GetPhoneNumberResponse } from './models/GetPhoneNumberResponse';
export type { GoodInfo } from './models/GoodInfo';
export type { InsertSuccessResult } from './models/InsertSuccessResult';
export type { LoginByCodeDto } from './models/LoginByCodeDto';
export type { LoginBySmsCodeDto } from './models/LoginBySmsCodeDto';
export type { LoginByWeixinDto } from './models/LoginByWeixinDto';
export type { LoginDto } from './models/LoginDto';
export type { MallCart } from './models/MallCart';
export type { MallCartBatchUpdateDto } from './models/MallCartBatchUpdateDto';
export type { MallCartCreateDto } from './models/MallCartCreateDto';
export type { MallCartGetAllResponse } from './models/MallCartGetAllResponse';
export type { MallCartUpdateDto } from './models/MallCartUpdateDto';
export type { MallGood } from './models/MallGood';
export type { MallGoodComment } from './models/MallGoodComment';
export type { MallGoodCommentCreateDto } from './models/MallGoodCommentCreateDto';
export type { MallGoodCommentPaginatePageInfo } from './models/MallGoodCommentPaginatePageInfo';
export type { MallGoodCommentPaginateResponse } from './models/MallGoodCommentPaginateResponse';
export type { MallGoodCommentPaginateWidthCursorPageInfo } from './models/MallGoodCommentPaginateWidthCursorPageInfo';
export type { MallGoodCommentPaginateWidthCursorResponse } from './models/MallGoodCommentPaginateWidthCursorResponse';
export type { MallGoodCreateDto } from './models/MallGoodCreateDto';
export type { MallGoodGetAllResponse } from './models/MallGoodGetAllResponse';
export type { MallGoodGetResponse } from './models/MallGoodGetResponse';
export type { MallGoodGroup } from './models/MallGoodGroup';
export type { MallGoodGroupCreateDto } from './models/MallGoodGroupCreateDto';
export type { MallGoodGroupGetAllResponse } from './models/MallGoodGroupGetAllResponse';
export type { MallGoodGroupGetResponse } from './models/MallGoodGroupGetResponse';
export type { MallGoodGroupGetTreeResponse } from './models/MallGoodGroupGetTreeResponse';
export type { MallGoodGroupUpdateDto } from './models/MallGoodGroupUpdateDto';
export type { MallGoodPaginatePage } from './models/MallGoodPaginatePage';
export type { MallGoodPaginateResponse } from './models/MallGoodPaginateResponse';
export { MallGoodRelation } from './models/MallGoodRelation';
export { MallGoodRelationCreateDto } from './models/MallGoodRelationCreateDto';
export type { MallGoodRelationGetResponse } from './models/MallGoodRelationGetResponse';
export type { MallGoodTabGetAllResponse } from './models/MallGoodTabGetAllResponse';
export type { MallGoodTag } from './models/MallGoodTag';
export type { MallGoodTagCreateDto } from './models/MallGoodTagCreateDto';
export type { MallGoodTagGetResponse } from './models/MallGoodTagGetResponse';
export type { MallGoodTagPaginatePageInfo } from './models/MallGoodTagPaginatePageInfo';
export type { MallGoodTagPaginateResponse } from './models/MallGoodTagPaginateResponse';
export type { MallGoodTagUpdateDto } from './models/MallGoodTagUpdateDto';
export type { MallGoodUpdateDto } from './models/MallGoodUpdateDto';
export type { MallOrder } from './models/MallOrder';
export type { MallOrderCreateDto } from './models/MallOrderCreateDto';
export type { MallOrderGetResponse } from './models/MallOrderGetResponse';
export type { MallOrderGood } from './models/MallOrderGood';
export type { MallOrderPageWidthCursorPageInfo } from './models/MallOrderPageWidthCursorPageInfo';
export type { MallOrderPageWidthCursorResponse } from './models/MallOrderPageWidthCursorResponse';
export type { MallOrderPaginatePageInfo } from './models/MallOrderPaginatePageInfo';
export type { MallOrderPaginateResponse } from './models/MallOrderPaginateResponse';
export type { MallShop } from './models/MallShop';
export type { MallShopCreateDto } from './models/MallShopCreateDto';
export type { MallShopGetAllResponse } from './models/MallShopGetAllResponse';
export type { MallShopGetResponse } from './models/MallShopGetResponse';
export type { MallShopPaginatePage } from './models/MallShopPaginatePage';
export type { MallShopPaginateResponse } from './models/MallShopPaginateResponse';
export type { MallShopUpdateDto } from './models/MallShopUpdateDto';
export type { Password } from './models/Password';
export { PathType } from './models/PathType';
export type { PhoneInfo } from './models/PhoneInfo';
export type { RecognizeAllText } from './models/RecognizeAllText';
export type { Resource } from './models/Resource';
export type { ResourceGetAllSuccessResult } from './models/ResourceGetAllSuccessResult';
export type { ResourceGetSuccessResult } from './models/ResourceGetSuccessResult';
export type { ResourcePaginateResult } from './models/ResourcePaginateResult';
export type { ResourcePaginateSuccessResult } from './models/ResourcePaginateSuccessResult';
export type { Role } from './models/Role';
export type { RoleGetAllSuccessResponse } from './models/RoleGetAllSuccessResponse';
export type { RoleGetSuccessResponse } from './models/RoleGetSuccessResponse';
export type { RolesPaginateResult } from './models/RolesPaginateResult';
export type { RolesPaginateSuccessResponse } from './models/RolesPaginateSuccessResponse';
export type { SendTemplateDto } from './models/SendTemplateDto';
export type { SessionGetUserResponse } from './models/SessionGetUserResponse';
export type { SessionInfo } from './models/SessionInfo';
export type { Setting } from './models/Setting';
export type { SettingGetItemsSuccessResponse } from './models/SettingGetItemsSuccessResponse';
export type { SettingSetDto } from './models/SettingSetDto';
export type { SmsTestDto } from './models/SmsTestDto';
export type { StoreItem } from './models/StoreItem';
export type { SuccessResult } from './models/SuccessResult';
export type { Token } from './models/Token';
export type { TreeDataResponse } from './models/TreeDataResponse';
export type { TreeNode } from './models/TreeNode';
export type { UpdateAiAliyunAccountDto } from './models/UpdateAiAliyunAccountDto';
export type { UpdateAiAliyunServiceDto } from './models/UpdateAiAliyunServiceDto';
export type { UpdateAiAliyunSessionDto } from './models/UpdateAiAliyunSessionDto';
export type { UpdateAiBaiduAccountDto } from './models/UpdateAiBaiduAccountDto';
export type { UpdateAiBaiduServiceDto } from './models/UpdateAiBaiduServiceDto';
export type { UpdateAiBaiduSessionDto } from './models/UpdateAiBaiduSessionDto';
export type { UpdateAiServiceTypeDto } from './models/UpdateAiServiceTypeDto';
export type { UpdateAiSessionDto } from './models/UpdateAiSessionDto';
export type { UpdateFDto } from './models/UpdateFDto';
export type { UpdateResourceDto } from './models/UpdateResourceDto';
export type { UpdateRoleDto } from './models/UpdateRoleDto';
export type { UpdateSuccessResult } from './models/UpdateSuccessResult';
export type { UploadFileInfo } from './models/UploadFileInfo';
export type { User } from './models/User';
export type { UserGetAllSuccessResponse } from './models/UserGetAllSuccessResponse';
export type { UserGetSuccessResponse } from './models/UserGetSuccessResponse';
export type { UsersBindMobileDto } from './models/UsersBindMobileDto';
export type { UsersBindUsernameDto } from './models/UsersBindUsernameDto';
export type { UsersBindWeixinDto } from './models/UsersBindWeixinDto';
export type { UsersPaginateResult } from './models/UsersPaginateResult';
export type { UsersPaginateSuccessResponse } from './models/UsersPaginateSuccessResponse';
export type { UserUpdateDto } from './models/UserUpdateDto';
export type { Watermark } from './models/Watermark';
export { Weixin } from './models/Weixin';
export type { WeixinCreateDto } from './models/WeixinCreateDto';
export type { WeixinGetAllResponse } from './models/WeixinGetAllResponse';
export type { WeixinGetSuccessResponse } from './models/WeixinGetSuccessResponse';
export type { WeixinMiniProgramCodeToSessionResponse } from './models/WeixinMiniProgramCodeToSessionResponse';
export type { WeixinOfficialAccountConfig } from './models/WeixinOfficialAccountConfig';
export type { WeixinOfficialAccountConfigGetByWeixinSuccessResponse } from './models/WeixinOfficialAccountConfigGetByWeixinSuccessResponse';
export type { WeixinOfficialAccountConfigUpdateDto } from './models/WeixinOfficialAccountConfigUpdateDto';
export type { WeixinOfficialAccountGetAccessTokenResponse } from './models/WeixinOfficialAccountGetAccessTokenResponse';
export type { WeixinOfficialAccountGetNotifyUrlResponse } from './models/WeixinOfficialAccountGetNotifyUrlResponse';
export type { WeixinPaginateResult } from './models/WeixinPaginateResult';
export type { WeixinPaginateSuccessResponse } from './models/WeixinPaginateSuccessResponse';
export type { WeixinPay } from './models/WeixinPay';
export type { WeixinPayCenterGetPayParamsDto } from './models/WeixinPayCenterGetPayParamsDto';
export type { WeixinPayCenterGetPayParamsResponse } from './models/WeixinPayCenterGetPayParamsResponse';
export type { WeixinPayCenterGetPayParamsResult } from './models/WeixinPayCenterGetPayParamsResult';
export type { WeixinPayCreateDto } from './models/WeixinPayCreateDto';
export type { WeixinPayGetResponse } from './models/WeixinPayGetResponse';
export type { WeixinPayPaginatePageInfo } from './models/WeixinPayPaginatePageInfo';
export type { WeixinPayPaginateResponse } from './models/WeixinPayPaginateResponse';
export type { WeixinPayUpdateDto } from './models/WeixinPayUpdateDto';
export type { WeixinPlatformUser } from './models/WeixinPlatformUser';
export type { WeixinPlatformUserPaginatePage } from './models/WeixinPlatformUserPaginatePage';
export type { WeixinPlatformUserPaginateResponse } from './models/WeixinPlatformUserPaginateResponse';
export type { WeixinUpdateDto } from './models/WeixinUpdateDto';

export { AddressService } from './services/AddressService';
export { AiAliyunAccountService } from './services/AiAliyunAccountService';
export { AiAliyunMessageService } from './services/AiAliyunMessageService';
export { AiAliyunOcrService } from './services/AiAliyunOcrService';
export { AiAliyunServiceService } from './services/AiAliyunServiceService';
export { AiAliyunSessionService } from './services/AiAliyunSessionService';
export { AiBaiduAccountService } from './services/AiBaiduAccountService';
export { AiBaiduMessageService } from './services/AiBaiduMessageService';
export { AiBaiduOcrService } from './services/AiBaiduOcrService';
export { AiBaiduServiceService } from './services/AiBaiduServiceService';
export { AiBaiduSessionService } from './services/AiBaiduSessionService';
export { AiCommonServiceTypeService } from './services/AiCommonServiceTypeService';
export { AreaService } from './services/AreaService';
export { AuthService } from './services/AuthService';
export { ChatContactsService } from './services/ChatContactsService';
export { ChatMessageService } from './services/ChatMessageService';
export { ChatSessionService } from './services/ChatSessionService';
export { DefaultService } from './services/DefaultService';
export { FileService } from './services/FileService';
export { ForumCommentService } from './services/ForumCommentService';
export { ForumPostService } from './services/ForumPostService';
export { ForumPostRelationService } from './services/ForumPostRelationService';
export { ForumSectionService } from './services/ForumSectionService';
export { FsService } from './services/FsService';
export { InitializationService } from './services/InitializationService';
export { MallCartService } from './services/MallCartService';
export { MallGoodService } from './services/MallGoodService';
export { MallGoodCommentService } from './services/MallGoodCommentService';
export { MallGoodGroupService } from './services/MallGoodGroupService';
export { MallGoodRelationService } from './services/MallGoodRelationService';
export { MallGoodTagService } from './services/MallGoodTagService';
export { MallOrderService } from './services/MallOrderService';
export { MallShopService } from './services/MallShopService';
export { ResourcesService } from './services/ResourcesService';
export { RolesService } from './services/RolesService';
export { SessionService } from './services/SessionService';
export { SettingService } from './services/SettingService';
export { SmsService } from './services/SmsService';
export { UsersService } from './services/UsersService';
export { WeixinService } from './services/WeixinService';
export { WeixinMiniProgramService } from './services/WeixinMiniProgramService';
export { WeixinOfficialAccountService } from './services/WeixinOfficialAccountService';
export { WeixinOfficialAccountConfigService } from './services/WeixinOfficialAccountConfigService';
export { WeixinOfficialAccountNotifyService } from './services/WeixinOfficialAccountNotifyService';
export { WeixinOfficialAccountOauthService } from './services/WeixinOfficialAccountOauthService';
export { WeixinPayService } from './services/WeixinPayService';
export { WeixinPlatformUserService } from './services/WeixinPlatformUserService';
